### ISSUE TITLE
SMS Message Not Matching Sent on Verizon iPhone 6

### ISSUE THREAD

**Issue by jadesym** [twilio/twilio-node#150]
Currently using version 3.3.0-edge

I have been trying to send a message across the Twilio platform. The message seems to work on other iPhones and a Nexus 5 as well as T-Mobile and AT&T, but the only differentiating factor for the broken one is Verizon. Other messages seem to work fine on the same phone after this one specific message for some reason. Additionally, if I look at the logs online at twilio.com, the message contents seem correct. Here is how this specific message looks:

![weird message clean](https://cloud.githubusercontent.com/assets/6668907/13278636/843d6840-da97-11e5-9e11-4e2681c2d300.jpg)

I can give more details via e-mail if this isn't quite clear enough.

**Comment by philnash** [comment]
Hey @jadesym, thanks for reporting this. As this seems to be an issue with different networks it's not best dealt with as part of the helper library issues. It's definitely a problem though! So, could you report this to help@twilio.com, ideally with some example message SIDs of messages that turned out like this.

Thanks!
