### ISSUE TITLE
Type Script Bindings

### ISSUE THREAD

**Issue by dcworldwide** [twilio/twilio-node#157]
### Feature Request

Please add typescript bindings so that developers who opt-in to using Twilio-Node with TypeScript, are able to take advantage of the TypeScript compiler to dramatically reduce the number of bugs created in their integration code.

**Comment by jamesflight** [comment]
+1

**Comment by ZuSe** [comment]
+1

**Comment by emanuelmd** [comment]
+1

**Comment by AlexLeung** [comment]
+1

**Comment by wongni** [comment]
+1

**Comment by bcdev-com** [comment]
+1

**Comment by gauravk92** [comment]
+1

**Comment by nickiannone** [comment]
I'm working on a declaration file for a minimal subset of the Twilio Node API for my own purposes, but it's extremely slow going due to the way they've designed the API itself. Most of the functionality is rolled together via mixins and generate, and there's a bunch of dynamically-constructed classes, so it's slow going. When I get a commit, it should be in nickiannone/DefinitelyTyped.

**Comment by nickiannone** [comment]
Update: The .d.ts file is complete(ish), and a PR is out to merge it into DefinitelyTyped. Check here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10528

**Comment by dkundel** [comment]
Great job @nickiannone! I'm working on TypeScript bindings for the client libraries and hopefully get that finished soon as well. 

Just a quick question what was your decision to push it into DefinintelyTyped rather than registering it with [typings](github.com/typings/typings)?

Overall awesome job taking the initiative here to get the ball rolling :+1:

**Comment by AlexLeung** [comment]
@dkundel How do you register with typings without pushing to DefinitelyTyped?

**Comment by dkundel** [comment]
You can add any repository in the [typings/registry](https://github.com/typings/registry). So you could host it in your own repository for example. But you can also just throw it into DefinitelyTyped and people can install it via `typings install dt~twilio`

**Comment by nickiannone** [comment]
The DefinitelyTyped PR has been merged. As for @dkundel's question, I pushed it to DT mostly just because I didn't know there was really an alternative, and it's easier for end-users. Now, there's a lot of hand-waving in my file, so if anyone wants to toy around with it and get it working better, bugfixes are definitely appreciated. Some of the resource mappings haven't been thoroughly tested because the documentation is super sparse, and I didn't know how, but this should be a good, solid starting point that covers 90% of functionality perfectly.

**Comment by carlososiel** [comment]
@dkundel Any advanced with the binding of twilio client for typescript2 that support the Device options?

**Comment by nickiannone** [comment]
I've stepped away from messing with this for now, due to no longer being on a client which uses Typescript with Twilio. I hope this has helped, but it's in someone else's hands now.

**Comment by jmctwilio** [comment]
The Node community did a great job here.  Thank you all for your contributions.  As I'm sure you noticed, the team at Twilio has been working hard to adopt code generation.  The workload without it is simply too great.  Having shipped Ruby, I hope to be better engaged with the community through github.  To those ends, I'd like to close this PR as it's very out of date.  Please open a new issue or PR as we truly value your contributions to the project.

**Comment by omidkrad** [comment]
related: https://github.com/twilio/twilio-node/issues/250

**Comment by omidkrad** [comment]
related: https://github.com/twilio/twilio-node/issues/250#issuecomment-360680866
