### ISSUE TITLE
Short SMSs getting "splat" into two SMSs when it finds a concatenated string.

### ISSUE THREAD

**Issue by AndyIbanez** [twilio/twilio-node#158]
I am concatenating simple strings in my program and what should be a short SMS gets separated into two when it finds a string concatenation with a variable. The context is that users can add mobile devices to their accounts and Twilio sends them an activation code generated by me.

Here's an screenshot of this behaviour:

![Spread Sms](http://i.imgur.com/6zZIoBc.jpg)

(Just look at the last two bubbles, as everything else may be confusing).

Now to the code.

The activation token is generated like this:

```JavaScript
var activationCode = crypto.randomBytes(32).toString('hex').slice(0, 6);
```

The actual code that sends the SMS (I have removed the irrelevant parts and kept the string building process):

```JavaScript

var SMS = require('./sms');

exports.sendPhoneActivationSMS = function(phoneNumber, activationCode, user, callback) {
	var message;

	var lang = user.language;

	if(lang == "es_ES") {
		message = "Su código de verificación es: " + activationCode + "";
	}

	var sms = new SMS.SMS(phoneNumber);
	sms.sendSMS(message, callback);
}
```

For the sake of completion, this is the whole SMS class (without the private Twilio info):

```JavaScript
var request = require('request');
var Twilio = require('twilio')(SID, AuthToken);

var SMS = exports.SMS = function(phoneNumber) {
	this.phoneNumber = phoneNumber;
};

// Callback: function(error, responseMessage)
SMS.prototype.sendSMS = function(message, callback) {

	if(message.length > 160) {
		callback(400, "The message cannot be longer than 160 characters.");
		return;
	}

	Twilio.sendSms({
		to: this.phoneNumber,
		from: TwilioPhoneNumber,
		body: message
	}, function(twilioerr, responseData) {
		if(twilioerr) {
			callback(400, twilioerr);
			return;
		} else {
			callback(null, "SMS Sent");
		}
	});
}

exports = SMS;
```

I see no reason the SMS should be splat into two. Even taking into account the Twilio demo notice, the message is shorter than 160 characters (i'm counting 72).

How should I go about dealing with this? I don't see anything abnormal when building the message string that would cause the code to be sent in a separate SMS.

**Version:** 1.1.x.

**Comment by philnash** [comment]
Hey @AndyIbanez,

I've worked out what's going on. The problem is that you're sending characters that don't exist in the [character set](https://en.wikipedia.org/wiki/GSM_03.38) that regular SMS messages fit in. I believe your issue is the "ó" character. When Twilio encounters a message like that, we have to send the SMS encoded as unicode, however that leaves you with a character limit of only 70 rather than the normal 160. It's explained in more depth in [this blog post](https://www.twilio.com/blog/2015/08/common-sms-problems-unicode-twilio.html).

The good news is that your message is only over 70 characters because you are still using a trial account and the message is prefixed with "Sent from your Twilio trial account - ". Once you upgrade your account, that message will go away and your message will happily fit within the 70 characters.

Does this all make sense?

**Comment by AndyIbanez** [comment]
Thanks. I did some tests yesterday and it looks like that's the case.

Unfortunately, this is just one of the SMS "types" we are going to send and some of them may be even longer. So I will just send messages without the special characters we use in Spanish, we should be a valid compromise for us.
