### ISSUE TITLE
It's hard to tell what arguments API functions accept

### ISSUE THREAD

**Issue by ericandrewlewis** [twilio/twilio-node#179]
The [documentation](http://twilio.github.io/twilio-node/) shows some examples of how to use the API, but it's hard to tell what all is possible.

e.g. what arguments does `client.messages.get()` accept?

It would be nice to see a list of API functions and their signatures.

**Comment by dkundel** [comment]
Hi @ericandrewlewis ,

Overall our helper library is just mirroring our REST API. So all options that you can pass are the "lowercased" version of the arguments described [here](https://www.twilio.com/docs/api/rest/message#list-get)

I hope that helps! Let me know if you have any other questions.

**Comment by lgomez** [comment]
+1 here.

I started by trying out this library but ended up switching to request because I could not figure out how to paginate over all the messages in our account. It's unclear how to do this even after reading through your API docs and this library's code. Could you provide an example?

Also, not sure where to report this but the numbers reported by the api don't add up. The total number of messages gotten from all the pages does not match the total reported by the api. Any ideas?

**Comment by jingming** [comment]
The latest version of the library lists out all the parameters that are supported in the docstring. You can also consult the latest jsdoc found here: http://twilio.github.io/twilio-node for all the valid parameters.
