### ISSUE TITLE
The From phone number +XXXXXXX is not a valid, SMS-capable inbound phone number or short code for your account 

### ISSUE THREAD

**Issue by lemonkazi** [twilio/twilio-node#199]
Hi I am using twilio trial account for test.
Here I used PHP code for sending sms
My id

           $config['account_sid']   = 'ACXXXXX';

	/**
	 * Auth Token
	 **/
	$config['auth_token']    = 'XXXXXX';

	/**
	 * API Version
	 **/
	$config['api_version']   = '2010-04-01';

	/**
	 * Twilio Phone Number
	 **/
	$config['number']        = '+XXXXXXXXX';

And to send sms I used

```
$sms_setting=$this->setting_model->get_setting_for_sms();
$client = new TwilioRestClient($sms_setting->account_sid,$sms_setting->auth_token);
// //$response =$this->twilio->request("/$ApiVersion/Accounts/$AccountSid/Calls", "POST", $data);
 $response = $this->twilio->sms($from,$to,$message,$sms_setting->account_sid,$sms_setting->config_number);
 if($response->IsError){
	echo 'Error: ' . $response->ErrorMessage;
 }
else
	 {
	//echo 'Sent message to ' . $to;
	 $this->session->set_flashdata('message', 'Message Sent');
					
 }


```
It now always sending that error.

**Comment by sschadwick** [comment]
Couple of notes:

You just compromised your api keys. I'm hoping these are your Test Credentials rather than full production, otherwise someone can impersonate your API interactions.

That being said, if they are indeed Test Credentials (and you own that number): Twilio will not recognize your owned phone numbers. You either have to switch to a 'magic number' or switch to your Production Credentials.

Lastly, this is the repo for Twilio-Node. [Here's the repo for Twilio-PHP](https://github.com/twilio/twilio-php).

Hope that helps!

**Comment by dkundel** [comment]
Hey @lemonkazi,

I'm a Developer Evangelist at Twilio.

I took out your credentials out of the issue you created here. Could you please reset your credentials using the [following instructions](https://support.twilio.com/hc/en-us/articles/223136027-Auth-Tokens-and-how-to-change-them) since you just exposed them to the internet.

Afterwards please create an issue at the [twilio-php](https://github.com/twilio/twilio-php) repo or send an email to help@twilio.com.

Thanks :)

**Comment by jingming** [comment]
Answered.

**Comment by magamlag** [comment]
Have the same issue as an author before. How possible to resolve it?

**Comment by jeanlaroche** [comment]
I had the same issue. In my case, it was just that I was trying to send an sms from a number that was a verified number, but not my twilio number (I had just registered with them, and hadn't created a twilio number yet). So I created a new twilio number, used that in send, and everything worked.
