### ISSUE TITLE
Confusing versioning plans

### ISSUE THREAD

**Issue by fiznool** [twilio/twilio-node#244]
The VERSIONS.md file states that:

> `twilio-node` uses a modified version of Semantic Versioning for all changes to the helper library

Having read through this document, I'd suggest that this isn't really anywhere close to semver, and in fact it's confusing to say that it is.

For example, semver advises that both the PATCH and MINOR numbers should only be incremented when a backwards compatible change is made. It also advocates the use of (e.g.) `-alpha.1` suffixes to denote a prerelease for that particular version - so `3.0.0-alpha.1` would be a prerelease of v3.

Using a different versioning scheme is of course your prerogative and I applaud the documenting of this in VERSIONS.md, but (IMHO) indicating a similarity to semver is misleading.

**Comment by jmctwilio** [comment]
@fiznool That's great feedback.  The reason we believe we're related to semver is that we increment the major version when there are backwards incompatible changes in our "General Availability"/mainline products.  Other products carry a notice that breaking changes aren't reflected in the major revision number.  Due to the fast pace of our development and the wide variety of products Twilio offers, we believe this versioning scheme is the best option among those we've considered.  It allows larger companies with onerous process to adopt our libraries for GA products while providing regular releases that keep pace with our growing portfolio of products.

That said, the team would very much appreciate any insights or recommendations you have regarding the versioning of our libraries.  We've already dropped our alpha branches and hope that the addendum to semver which distinguishes mainline/GA products from developer preview or beta products is as intuitive as possible for all of our users and contributors.
