### ISSUE TITLE
Extend support of older library

### ISSUE THREAD

**Issue by datfinesoul** [twilio/twilio-node#268]
Version 3.0.0 of this library went live on 2017-05-03

Based on your notes:

> The old library (2.x) will be officially supported until 8/31/2017. After that day, Twilio will stop providing bug fixes and Support might ask you to upgrade before debugging issues.

Giving your users 3 months to migrate bigger systems to the new library seems a bit rushed, especially given that within the first hour of working with the new library I'm starting to find quite a few bugs and inconsistencies.  (I'll file those separately as soon as I have time)

Could you possibly extend your support a bit further out?

**Comment by dougblack** [comment]
Hey @datfinesoul, I'm the tech lead of the API team here at Twilio. We're the ones responsible for maintaining the six Twilio helper libraries, and for coming up with the deprecation plan referenced on [this page](https://www.twilio.com/docs/libraries/node/migration-guide).

I agree that three months from release to drop-support is quite fast, but we aren't well positioned at the moment to support all six old libraries and all twelve (mainline + alpha) new libraries and so the relatively aggressive timeline was what we arrived at. The old libraries across all six languages have unfortunately been missing features for years as Twilio's rate of growth quickly outpaced one team's ability to handcraft new product support into six different languages. We've solved this by betting heavily on code generation, which is why feature parity across all six languages (next-gen Ruby is landing very soon) is as good as its ever been.

The old libraries have effectively been in maintenance mode for over a year now, even missing entire product lines, as we've been busy teaching our code generator to generate their replacements. Until 8/31/2017, we're committed to addressing any security concerns in the old library, but after that date we'll be asking customers to upgrade first as we expect upgrading to address the vast majority of bugs customers experience in the old library.

You should expect inconsistencies between the old and new versions--all six libraries have been rewritten from the ground up--but bugs aren't alright. Please let us know what you're seeing and we'll be sure to tackle right away.

**Comment by datfinesoul** [comment]
Thanks for the response.  I definitely like that the library is finally getting attention again.  I'll submit the bugs once I re-install and reproduce the issues.
