### ISSUE TITLE
Validating Requests With Query String

### ISSUE THREAD

**Issue by chadwhitaker** [twilio/twilio-node#306]
It appears that the `validateExpressRequest` function is no longer validating endpoints that contain a query param in the URL. Also, GET requests cannot be validated regardless of a query param.

Ref: https://github.com/twilio/twilio-node/issues/145

**Comment by chadwhitaker** [comment]
cc: @jmctwilio

**Comment by alexcchan** [comment]
@chadwhitaker and I touched base on this.  It looks like the root cause of validation failures is because `url.format` expects the `pathname` option to exclude query string, whereas Express `request.originalUrl` includes query string.

When `request.originalUrl` includes query string, the `?` separator gets URL-encoded by `url.format` as `%3F`, breaking the validation.

https://github.com/twilio/twilio-node/blob/master/lib/webhooks/webhooks.js#L50
https://nodejs.org/api/url.html#url_url_format_urlobject
http://expressjs.com/en/api.html#req.originalUrl

#311 is one way to work around this issue, but may not be the best way.

**Comment by chadwhitaker** [comment]
Fixed via https://github.com/twilio/twilio-node/pull/311
