### ISSUE TITLE
Syntax error in twilio-node library

### ISSUE THREAD

**Issue by sasincj** [twilio/twilio-node#333]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**
Node version : 8.10.0
twilio-node : 3.14.0

### Code Snippet
```node
https://github.com/twilio/starter-node/blob/master/app.js
```

### Exception/Log
```
..\node_modules\twilio\lib\rest\accounts\v1\credential\aws.js:511
  let clone = {};
  ^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (..\node_modules\twilio\lib\rest\accounts\v1\credential.js:13:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

### Steps to Reproduce
1. copied app.js and tried to run on cmd line using command "node app.js"
2. just after that above mentioned error was thrown
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by dkundel** [comment]
Hey @sasincj,

This seems to be the wrong error message for the actual problem. The project that you found is largely deprecated at the moment since it uses our old version 2.x of the helper library. I went ahead and marked it as deprecated now. Sorry to see you being blocked by that.

Maybe check out the tutorials on the Twilio Docs as they might have something for your use case: https://www.twilio.com/docs/tutorials?order_by=-popularity_rank&filter-language=node

Let me know if I can help out with anything. In the meantime I'll close this issue.

Cheers,
Dominik
