### ISSUE TITLE
Can't instantiate client in typescript: Only a void function can be called with the 'new' keyword

### ISSUE THREAD

**Issue by jessep** [twilio/twilio-node#383]
**Version: 3.19.2**

### Code Snippet
```node
import * as TwilioApi from 'twilio';
const twilio = new TwilioApi('sid', 'secret');
```

### Exception/Log
```
Typescript error: Only a void function can be called with the 'new' keyword 
```
If you don't use `new` keyword, the constructor doesn't get called and there's a different error. I'm just going to use the REST Api directly, but this was certainly annoying/disappointing. I'd normally just ignore it, but I'm using Google Cloud functions, and don't want to turn off their TS based safety feature, which prevents code that throws errors from deploying.

### Steps to Reproduce
1. Use typescript with twilio-node
2. Try to instantiate a client
3. Breaks

**Comment by dkundel** [comment]
Hey @jessep! I'm sorry for the caused pain.

The problem is that we are currently generating the TS bindings for the JS lib instead of writing the library in TS. The way the JS library currently is written causes the problem that we had to make the call whether the base export is a function or a class instead of both. Right now it's a function since that's technically the implementation in JS.

This means this should work:
```ts
import TwilioApi = require('twilio');
const twilio = TwilioApi('sid', 'secret');
```

Please let me know if this solves your problem.

Cheers,
Dominik

**Comment by jessep** [comment]
Ha, okay, figured it out. I had already tried what you suggested, and it failed with `accountSid is required`. Tried it again though, and looking the line that failed, I realize that I was using the wrong token pair, not that the parameter wasn't get passed through. Thanks for the nudge!

**Comment by stoplion** [comment]
Is this still and issue? I am getting same error (Dec 2020)

**Comment by j0hnm4r5** [comment]
I too am getting this issue as of Feb 2021

**Comment by philnash** [comment]
I have been using the Twilio library (see this post on [sending SMS messages with Twilio in TypeScript](https://www.twilio.com/blog/send-sms-typescript-twilio)) like this:

```typescript
import { Twilio } from "twilio";
const client = new Twilio(accountSid, authToken);
```

This picks out the actual Twilio API client.
