### ISSUE TITLE
answerOnBridge flag disrupts call flow

### ISSUE THREAD

**Issue by alfietinkerve** [twilio/twilio-node#759]
### Issue Summary
Call flow for inbound and outbound voice SDK are disrupted caused from the use of the `answerOnBridge` flag in Voice Response. Noticeable changes, one of it, is on the request header of the endpoint events, one which has call_sid (false) another does not (true). Through back end callback logs, it is discovered that temp callSID is passed from Twilio through the endpoint rather than callSID, which explains the event being fired but no reaction on the call connection due to mismatched/undefined SID, theoratically speaking.

Affected call flow: -
**Outbound**

Start a call -> ringing -> caller disconnect() -> receiver still ringing
Start a call -> ringing -> receiver reject -> caller still ringing

**Inbound**

Incoming call -> ringing -> receiver reject -> caller still ringing
Incoming call -> ringing -> accepted -> disconnect() -> caller still in call

### Steps to Reproduce
1. Set answerOnBridge flag to `true`
2. Commence any call flow using voice-sdk

### Code Snippet
```
const r = new twilio.twiml.VoiceResponse();
    const dialAttributes = {
      callerId: req.serviceUser.phoneNumber,
      answerOnBridge: true,
    };
```

### Exception/Log
```

```

### Technical details:
* twilio-node version: 3.72.0
* node version: 16.15.1

**Comment by beebzz** [comment]
Hi @alfietinkerve, thanks for submitting an issue. The `answerOnBridge` flag, when set to true and when `<Dial>` is the first verb in a Twiml doc, persists an outbound call until the recipient answers it (per the [documentation](https://www.twilio.com/docs/voice/twiml/dial#answeronbridge)).

If your issue is with the behavior of the API, please open a [support ticket](https://twilio.com/help/contact) in order to properly debug this issue. Otherwise, if it's with the behavior of the library, feel free to elaborate more on what it is.
