### ISSUE TITLE
 ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)

### ISSUE THREAD

**Issue by uchsarath** [twilio/twilio-node#85]
I used this module

exports.sendRegistrationSMS = function(registration){
    client.sms.messages.create({
        to:      '+85578887887',
        from:   cfg.TWILLIO.PHONE,
        body:   'Your PIN code: ' + registration.pin
    }, function(error, message) {
        if(error) log.debug('Sent SMS Error' + error.status);
        else {
            log.debug('Successfully Sent SMS to phone number: ' +
            registration.phone + 'with SMS ID: ' +
            message.sid);
        }
    });

In console it return this error message.

ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)

**Comment by kwhinnery** [comment]
Not sure I fully understand the problem - I would recommend sending a note to help@twilio.com with a full code example that doesn't work, and let them know what the expected behavior is.  We can help troubleshoot more effectively there. The GitHub issues are used only for actual issues with the module.

Thanks,
-Kevin
