### ISSUE TITLE
not able to make doc Phone Number Lookups example to work

### ISSUE THREAD

**Issue by fabriziomoscon** [twilio/twilio-node#95]
Hi Kevin,
I am trying out the code at https://www.twilio.com/docs/api/rest/lookups#lookup-get-basic-example-2

node v0.10.37
library 2.2.0
OS Linux 3.13.0-48-generic Ubuntu

```javascript
var accountSid = 'AC3094732a3c49700934481addd5ce1659';
var authToken = "{{ auth_token }}";
var client = require('twilio').LookupsClient(accountSid, authToken);
 
client.phoneNumbers.get("(510) 867-5309", {countryCode: "US", type: "carrier"}, function(error, number) {
    process.stdout.write(number.phoneNumber);
});
```

and I am getting the following error:

```
TypeError: Cannot read property 'phoneNumbers' of undefined
    at Object.<anonymous> (/home/fabrizio/projects/bizzby/integration-test/sms/lookup.js:17:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

but the following works fine for me

```javascript
var accountSid = "MY_LIVE_SID"
var authToken = "MY_AUTH_TOKEN"

var twilio = require('twilio')
var client = new twilio.LookupsClient(accountSid, authToken)

client.phoneNumbers("VALID_GB_MOBILE").get({countryCode: 'GB', type: 'carrier'},function(err, number) {
  console.log(err, number)
})
```

What should I use? Is the documentation outdated?

Are there any changes in using `new` I should be aware of between `1.6.x` and `2.2.0` I can see few of the `node.js` examples are not using `new` at all to instantiate the client, but my master code is initiating the client using `new` with `1.6.x`
Could you point me to a place where to find a list of all the API breaking changes adopted in `2.2.0` as I am planning to update my library version on production. @kwhinnery

**Comment by kwhinnery** [comment]
Sorry for the super late reply here - the Node.js example code in the API reference was incorrect. It has since been updated - the `new` keyword is required for all API clients.

The only breaking change in 2.x was removing paging properties from response payloads, as discussed here:

https://www.twilio.com/engineering/2015/04/16/replacing-absolute-paging-with-relative-paging

Other than that, the API is largely unchanged.

**Comment by fabriziomoscon** [comment]
Thanks!

**Comment by morgs32** [comment]
Not sure what example @fabriziomoscon is speaking of. I had to resort to looking in the code in order to know Lookups was in twilio-node. Never would've figured out how to use it had I not seen this question. Lucky for me, I found it before chucking my computer out the window. Save some other schmuck from defenestrating his computer by updating docs?
