### ISSUE TITLE
Node.js v20 support

### ISSUE THREAD

**Issue by electrovir** [twilio/twilio-node#980]
Node.js v20 is [now the latest LTS version of Node.js](https://github.com/nodejs/Release/blob/2562cb2310658085f3042a5b2f745d8ee015c447/README.md). Can this package support it please?

**Comment by rvitaliy** [comment]
according to packege.json configuration this vendor support `"node": ">=14.0"` see: https://github.com/twilio/twilio-node/blob/main/package.json#L76
but in the README say that it support only 14,16,18 https://github.com/twilio/twilio-node/blob/main/README.md?plain=1#L20
currently i use it on nodejs 20.9.0 without problem, but yes it's not the best solution since the tests runs only on 14,16,18 see: https://github.com/twilio/twilio-node/blob/main/.github/workflows/test-and-deploy.yml#L20C12-L20C12

please, can you start support nodejs v20 on your test suite too. 🙏

**Comment by tiwarishubham635** [comment]
The support for node v20 has been temporarily removed due to an existing open issue with node v20. We are looking into it and will soon provide support for the LTS version of node.

**Comment by jordan-bite** [comment]
@tiwarishubham635 Can you provide link to where this is currently being tracked?

**Comment by Joeao** [comment]
I believe that this issue can be closed as of the release of [4.20.1](https://github.com/twilio/twilio-node/releases/tag/4.20.1)

**Comment by tiwarishubham635** [comment]
LTS Support is added in [4.20.1](https://github.com/twilio/twilio-node/releases/tag/4.20.1). Closing this issue.
